import {Component,ViewChild,ElementRef,ComponentFactoryResolver,ViewContainerRef,forwardRef,ContentChildren,QueryList} from '@angular/core';
import { base } from './base';
// Ext Class - Ext.calendar.view.Week
export class calendar_weekviewMetaData {
	public static XTYPE: string = 'calendar-weekview';
	public static INPUTNAMES: string[] = [
		'addForm',
		'allowSelection',
		'ariaAttributes',
		'ariaDescribedBy',
		'ariaLabel',
		'ariaLabelledBy',
		'bind',
		'border',
		'cls',
		'compact',
		'compactOptions',
		'controller',
		'controlStoreRange',
		'defaultListenerScope',
		'disabled',
		'displayOverlap',
		'draggable',
		'droppable',
		'editForm',
		'endTime',
		'eventDefaults',
		'eventHandlers',
		'firstDayOfWeek',
		'focusCls',
		'gestureNavigation',
		'header',
		'height',
		'hidden',
		'hideMode',
		'instanceCls',
		'keyMap',
		'keyMapEnabled',
		'keyMapTarget',
		'listeners',
		'name',
		'nameable',
		'plugins',
		'publishes',
		'reference',
		'renderTo',
		'resizeEvents',
		'ripple',
		'session',
		'shareableName',
		'showNowMarker',
		'startTime',
		'store',
		'style',
		'timeFormat',
		'timeRenderer',
		'timezoneOffset',
		'touchAction',
		'twoWayBindable',
		'ui',
		'userCls',
		'value',
		'viewModel',
		'visibleDays',
		'width',
		'flex',
		'platformConfig',
		'responsiveConfig',
		'fitToParent',
		'config'
];
	public static OUTPUTS: any[] = [
		{name:'beforedisabledchange',parameters:'sender,value,oldValue,undefined'},
		{name:'beforeeventadd',parameters:'calendar-weekview,context'},
		{name:'beforeeventdragstart',parameters:'calendar-weekview,context'},
		{name:'beforeeventedit',parameters:'calendar-weekview,context'},
		{name:'beforeeventresizestart',parameters:'calendar-weekview,context'},
		{name:'beforeheightchange',parameters:'sender,value,oldValue,undefined'},
		{name:'beforehiddenchange',parameters:'sender,value,oldValue,undefined'},
		{name:'beforewidthchange',parameters:'sender,value,oldValue,undefined'},
		{name:'blur',parameters:'calendar-weekview,event'},
		{name:'disabledchange',parameters:'sender,value,oldValue'},
		{name:'eventadd',parameters:'calendar-weekview,context'},
		{name:'eventdrop',parameters:'calendar-weekview,context'},
		{name:'eventedit',parameters:'calendar-weekview,context'},
		{name:'eventresize',parameters:'calendar-weekview,context'},
		{name:'eventtap',parameters:'calendar-weekview,context'},
		{name:'focus',parameters:'calendar-weekview,event'},
		{name:'focusenter',parameters:'calendar-weekview,event'},
		{name:'focusleave',parameters:'calendar-weekview,event'},
		{name:'heightchange',parameters:'sender,value,oldValue'},
		{name:'hiddenchange',parameters:'sender,value,oldValue'},
		{name:'validateeventadd',parameters:'calendar-weekview,context'},
		{name:'validateeventdrop',parameters:'calendar-weekview,context'},
		{name:'validateeventedit',parameters:'calendar-weekview,context'},
		{name:'validateeventresize',parameters:'calendar-weekview,context'},
		{name:'valuechange',parameters:'calendar-weekview,context'},
		{name:'widthchange',parameters:'sender,value,oldValue'},
		{name:'ready',parameters:''}
];
	public static OUTPUTNAMES: string[] = [
		'beforedisabledchange',
		'beforeeventadd',
		'beforeeventdragstart',
		'beforeeventedit',
		'beforeeventresizestart',
		'beforeheightchange',
		'beforehiddenchange',
		'beforewidthchange',
		'blur',
		'disabledchange',
		'eventadd',
		'eventdrop',
		'eventedit',
		'eventresize',
		'eventtap',
		'focus',
		'focusenter',
		'focusleave',
		'heightchange',
		'hiddenchange',
		'validateeventadd',
		'validateeventdrop',
		'validateeventedit',
		'validateeventresize',
		'valuechange',
		'widthchange',
		'ready'
];
}
@Component({
  selector: calendar_weekviewMetaData.XTYPE,
	inputs: calendar_weekviewMetaData.INPUTNAMES,
	outputs: calendar_weekviewMetaData.OUTPUTNAMES,
	providers: [{provide: base, useExisting: forwardRef(() => calendar_weekview)}],
	template: '<ng-template #dynamic></ng-template>'
})
export class calendar_weekview extends base {
	constructor(eRef:ElementRef,resolver:ComponentFactoryResolver,vcRef:ViewContainerRef) {
		super(eRef,resolver,vcRef,calendar_weekviewMetaData);
	}
	//@ContentChildren(base,{read:ViewContainerRef}) extbaseRef:QueryList<ViewContainerRef>;
	@ContentChildren(base,{read: base}) extbaseRef: QueryList<base>;
	@ViewChild('dynamic',{read:ViewContainerRef}) dynamicRef:ViewContainerRef;
	ngAfterContentInit() {this.AfterContentInit(this.extbaseRef);}
	ngOnInit() {this.OnInit(this.dynamicRef,calendar_weekviewMetaData);}
}
